module.exports = [
  {
    format: "cEDH",
    name: "Hinata's Golden Crown",
    archetype: "Control/Combo",
    img: "/images/Hinata.jpeg",
    lands: [
      "Training Center",
      "Volcanic Island",
      "Arid Mesa",
      "Hallowed Fountain",
      "Tundra",
      "Tarnished Citadel",
      "Sea of Clouds",
      "Otawara, Soaring City",
      "Island",
      "Scalding Tarn",
      "Gemstone Caverns",
      "Steam Vents",
      "Sunbaked Canyon",
      "Forbidden Orchard",
      "Battlefield Forge",
      "Tolaria West",
      "Flooded Strand",
      "Ancient Tomb",
      "City of Brass",
      "Clifftop Retreat",
      "Cascade Bluffs",
      "Plains",
      "Marsh Flats",
      "Spectator Seating",
      "Furycalm Snarl",
      "Sulfur Falls",
      "Sacred Foundry",
      "Plateau",
      "Mountain",
      "Glacial Fotress",
      "Mystic Gate",
      "Command Tower",
    ],
    creatures: [
      "Hinata, Dawn-Crowned",
      "Drannith Magistrate",
      "Sanctum Prelate",
      "Gilded Drake",
      "Thalia, Guardian of Thraben",
      "Auriok Salvagers",
      "Esper Centinal",
      "Tribute Mage",
      "Trophy Mage",
      "Zirda, the Dawnwaker",
      "Aven Mindsensor",
      "Spellseeker",
      "Lavinia, Azorius Renegade",
      "Dockside Extortionist",
      "Thassa's Oracle",
    ],
    planeswalkers: ["Teferi, Time Raveler"],
    artifacts: [
      "Mox Diamond",
      "Mana Vault",
      "Rings of Brighthearth",
      "Fellwar Stone",
      "Chrome Mox",
      "Arcane Signet",
      "Lotus Petal",
      "Grim Monolith",
      "Basalt Monolith",
      "Sol Ring",
      "Lion's Eye Diamond",
      "Mana Crypt",
      "Sphere of Resistance",
      "Isochron Scepter",
      "Knowledge Pool",
    ],
    instants: [
      "Flawless Maneuver",
      "Brain Freeze",
      "Force of Will",
      "Dramatic Reversal",
      "Force of Negation",
      "Sublime Epiphany",
      "Aurelia's Fury",
      "Mana Drain",
      "Angel's Grace",
      "Red Elemental Blast",
      "Muddle the Mixture",
      "Delay",
      "Bolt Bend",
      "Doven's Veto",
      "Mana Tithe",
      "Flusterstorm",
      "Intuition",
      "Swan Song",
      "Pyroblast",
      "Mystical Tutor",
      "Predict",
      "Pact of Negation",
      "Silence",
      "Deflecting Swat",
      "Fierce Guardianship",
      "Mental Misstep",
      "Comet Storm",
    ],
    sorceries: [
      "Windfall",
      "Wheel of Fortune",
      "Gamble",
      "Fireball",
      "Jeska's Will",
      "Gitaxian Probe",
    ],
    enchantments: [
      "Underworld Breach",
      "Whirlwind of Thought",
      "Mystic Remora",
      "Rhystic Study",
    ],
  },
];
