module.exports = [
  {
    format: "Modern",
    name: "Domain Zoo",
    archetype: "Aggro",
    img: "https://mtgtop8.com/metas_thumbs/300.jpg",
    lands: [
      "Bloodstained Mire x1",
      "Blood Crypt x1",
      "Breeding Pool x1",
      "Savai Triome x1",
      "Scalding Tarn x1",
      "Steam Vents x1",
      "Temple Garden x1",
      "Stomping Ground x1",
      "Zagoth Triome x1",
      "Forest x1",
      "Mountain x1",
      "Wiundswept Heath x4",
      "Wooded Foothills x4",
    ],
    creatures: [
      "Noble Heirarch x3",
      "General Ferrous Rokiric x2",
      "Territorail Kavu x 4",
      "Mantis Rider x4",
      "Bloodbraid Elf x4",
      "Scion of Draco x4",
      "Ignoble Heirarch x 3",
      "Shardless agent x 3",
    ],
    planeswalkers: ["Wrenn and Six x2"],
    artifacts: "",
    instants: ["Lightning Bolt x4", "Lightning Helix x 4", "Tribal Flamesx 4"],
    sorceries: "",
    enchantments: "",
  },
];
